### ISSUE TITLE
[ Feat ] : Can Set Number Range 

### ISSUE THREAD

**Issue by AKACHI-4** [KiranPolaki/GuessTheNumber-Game-JS#36]
## What ?

I am thinking that if a player can set the value or range for guessing the number, and I make sure that the range is not less than 10, I will use the same retro style.

## Screenshots

![image](https://github.com/KiranPolaki/GuessTheNumber/assets/99159580/34d53ca8-7e92-448a-9d24-31d88fbaba67)

## Code of Conduct

- [x] I agree to follow this project's Code of Conduct

<br>

> **Kindly assign it to me under _HacktoberFest'23_** 
> **I will surely complete it ASAP**

**Comment by AKACHI-4** [comment]
> Warm welcome to open source if u are new😀🥂

Hey @KiranPolaki ... Thanks for welcoming, Greetings !

> like are you proposing you want the user to decide in what range they want to play this game?

Yah ..

**Comment by KiranPolaki** [comment]
great idea!

but can u elaborate where u will add this input field is that like a popup or or just a normal field without disturbing the look and feel of the game!

**Comment by AKACHI-4** [comment]
not popup; so in place of 20 there would be a field where u can set, intially it will be 10 and as I mentioned that the range can't be less then 10 coz then there will be no sense to guessing number for smaller range.

**Comment by KiranPolaki** [comment]
make it 20 as default 

And make sure you also set the score and high score with respective to the value user inputs!

do let me know what are your opinions on this🤔. is it okay if we keep score as 20 or will it make more sense if we also change that!🤔

**Comment by AKACHI-4** [comment]
> make it 20 as default
 
> And make sure you also set the score and high score with respective to the value user inputs!

> do let me know what are your opinions on this🤔. is it okay if we keep score as 20 or will it make more sense if we also change that!🤔

no problem .... default 20 is also okay .. and then it will be limit too and player can set range more then 20 always.. 

nd ya i'll keep it in mind that score and high score also with in sync..

**Comment by KiranPolaki** [comment]
Assigned💥

**Comment by AKACHI-4** [comment]
Thanks will cmplt ASAP.
